### ISSUE TITLE
NullPointerException when try convert to rdf

### ISSUE THREAD

**Issue by Hronom** [Wikidata/Wikidata-Toolkit#159]
I use version from maven central:
```XML
<dependency>
    <groupId>org.wikidata.wdtk</groupId>
    <artifactId>wdtk-dumpfiles</artifactId>
    <version>0.4.0</version>
</dependency>
<dependency>
    <groupId>org.wikidata.wdtk</groupId>
    <artifactId>wdtk-rdf</artifactId>
    <version>0.4.0</version>
</dependency>
```

Here is the log:
```
[main] INFO org.wikidata.wdtk.dumpfiles.wmf.WmfDumpFileManager - Using download directory data_sources\wikidata\sources\dumpfiles\wikidatawiki
[main] INFO org.wikidata.wdtk.dumpfiles.wmf.WmfDumpFileManager - Found 1 local dumps of type SITES: [wikidatawiki-sites-20150704]
[main] INFO org.wikidata.wdtk.dumpfiles.wmf.WmfDumpFileManager - Found 11 online dumps of type SITES: [wikidatawiki-sites-20150704, wikidatawiki-sites-20150603, wikidatawiki-sites-20150526, wikidatawiki-sites-20150423, wikidatawiki-sites-20150330, wikidatawiki-sites-20150307, wikidatawiki-sites-20150207, wikidatawiki-sites-20150204, wikidatawiki-sites-20150113, wikidatawiki-sites-20141208, wikidatawiki-sites-20141205]
[main] INFO org.wikidata.wdtk.dumpfiles.MwSitesDumpFileProcessor - Processing sites dump file wikidatawiki-sites-20150704
[main] INFO org.wikidata.wdtk.dumpfiles.wmf.WmfDumpFileManager - Using download directory data_sources\wikidata\sources\dumpfiles\wikidatawiki
[main] INFO org.wikidata.wdtk.dumpfiles.wmf.WmfDumpFileManager - Found 1 local dumps of type JSON: [wikidatawiki-json-20150727]
[main] INFO org.wikidata.wdtk.dumpfiles.wmf.WmfDumpFileManager - Found 11 online dumps of type JSON: [wikidatawiki-json-20150727, wikidatawiki-json-20150720, wikidatawiki-json-20150713, wikidatawiki-json-20150706, wikidatawiki-json-20150629, wikidatawiki-json-20150622, wikidatawiki-json-20150615, wikidatawiki-json-20150608, wikidatawiki-json-20150601, wikidatawiki-json-20150525, wikidatawiki-json-20150518]
[main] INFO org.wikidata.wdtk.dumpfiles.JsonDumpFileProcessor - Processing JSON dump file wikidatawiki-json-20150727
[main] WARN org.wikidata.wdtk.rdf.RdfConverter - Unknown Wikimedia language code "lzz". Using this code in RDF now, but this might be wrong.
[main] INFO org.wikidata.wdtk.rdf.WikidataPropertyTypes - Fetching datatype of property P1245 online.
[main] ERROR org.wikidata.wdtk.rdf.WikidataPropertyTypes - com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@3cbea6af; line: 1, column: 1]
[main] INFO org.wikidata.wdtk.rdf.WikidataPropertyTypes - Fetching datatype of property P1051 online.
[main] ERROR org.wikidata.wdtk.rdf.WikidataPropertyTypes - com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@5c3d0083; line: 1, column: 1]
[main] INFO org.wikidata.wdtk.dumpfiles.EntityTimerProcessor - Starting processing.
[main] WARN org.wikidata.wdtk.rdf.RdfConverter - Unknown Wikimedia language code "lzz". Using this code in RDF now, but this might be wrong.
[main] INFO org.wikidata.wdtk.rdf.WikidataPropertyTypes - Fetching datatype of property P1245 online.
[main] ERROR org.wikidata.wdtk.rdf.WikidataPropertyTypes - com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@2ddef689; line: 1, column: 1]
[main] INFO org.wikidata.wdtk.rdf.WikidataPropertyTypes - Fetching datatype of property P1296 online.
[main] ERROR org.wikidata.wdtk.rdf.WikidataPropertyTypes - com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@90bb3e6; line: 1, column: 1]
[main] INFO org.wikidata.wdtk.rdf.WikidataPropertyTypes - Fetching datatype of property P1051 online.
[main] ERROR org.wikidata.wdtk.rdf.WikidataPropertyTypes - com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@5f4fc5ad; line: 1, column: 1]
[main] INFO org.wikidata.wdtk.rdf.WikidataPropertyTypes - Fetching datatype of property P1628 online.
[main] ERROR org.wikidata.wdtk.rdf.WikidataPropertyTypes - com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@d895756; line: 1, column: 1]
[main] INFO org.wikidata.wdtk.rdf.WikidataPropertyTypes - Fetching datatype of property P1365 online.
[main] ERROR org.wikidata.wdtk.rdf.WikidataPropertyTypes - com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@64347412; line: 1, column: 1]
Exception in thread "main" java.lang.NullPointerException
	at org.wikidata.wdtk.rdf.SnakRdfConverter.getRangeUri(SnakRdfConverter.java:305)
	at org.wikidata.wdtk.rdf.SnakRdfConverter.visit(SnakRdfConverter.java:199)
	at org.wikidata.wdtk.rdf.SnakRdfConverter.visit(SnakRdfConverter.java:54)
	at org.wikidata.wdtk.datamodel.json.jackson.JacksonNoValueSnak.accept(JacksonNoValueSnak.java:47)
	at org.wikidata.wdtk.rdf.RdfConverter.writeClaim(RdfConverter.java:398)
	at org.wikidata.wdtk.rdf.RdfConverter.writeStatement(RdfConverter.java:372)
	at org.wikidata.wdtk.rdf.RdfConverter.writeStatements(RdfConverter.java:242)
	at org.wikidata.wdtk.rdf.RdfConverter.writeItemDocument(RdfConverter.java:176)
	at org.wikidata.wdtk.rdf.RdfSerializer.processItemDocument(RdfSerializer.java:131)
	at org.wikidata.wdtk.datamodel.interfaces.EntityDocumentProcessorBroker.processItemDocument(EntityDocumentProcessorBroker.java:59)
	at org.wikidata.wdtk.dumpfiles.JsonDumpFileProcessor.handleDocument(JsonDumpFileProcessor.java:128)
	at org.wikidata.wdtk.dumpfiles.JsonDumpFileProcessor.processDumpFileContents(JsonDumpFileProcessor.java:89)
	at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processDumpFile(DumpProcessingController.java:559)
	at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processDump(DumpProcessingController.java:495)
	at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processMostRecentJsonDump(DumpProcessingController.java:459)
```

**Comment by guenthermi** [comment]
This bug is caused by recent changes in the Wikidata API. We provided a fix in the current version of WDTK but the fix is not in the current maven release.

**Comment by Hronom** [comment]
Thanks for answer!
When this will be available in maven?

**Comment by mkroetzsch** [comment]
We plan to have a new release this month, after some more patches have been integrated.

**Comment by mkroetzsch** [comment]
The underlying problem that causes this bug to surface is that WDTK does not follow redirects. This is tracked at #151.
