### ISSUE TITLE
Deserialization failure on dumps with redirects

### ISSUE THREAD

**Issue by Tpt** [Wikidata/Wikidata-Toolkit#240]
The Wikidata daily XML dumps contains serialization for redirects.

Wikidata Toolkit 0.7 fails when deserializing them:

``` java
GRAVE: Failed to map JSON for item Q26790101: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class org.wikidata.wdtk.datamodel.json.jackson.JacksonItemDocument)
 at [Source: {"entity":"Q26790101","redirect":"Q21863925"}; line: 1, column: 45]
com.fasterxml.jackson.databind.JsonMappingException: Unexpected token (END_OBJECT), expected FIELD_NAME: missing property 'type' that is to contain type id  (for class org.wikidata.wdtk.datamodel.json.jackson.JacksonItemDocument)
 at [Source: {"entity":"Q26790101","redirect":"Q21863925"}; line: 1, column: 45]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:927)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedUsingDefaultImpl(AsPropertyTypeDeserializer.java:151)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:103)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeWithType(BeanDeserializerBase.java:966)
    at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:42)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1443)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1081)
    at org.wikidata.wdtk.dumpfiles.WikibaseRevisionProcessor.readValue(WikibaseRevisionProcessor.java:160)
    at org.wikidata.wdtk.dumpfiles.WikibaseRevisionProcessor.processItemRevision(WikibaseRevisionProcessor.java:97)
    at org.wikidata.wdtk.dumpfiles.WikibaseRevisionProcessor.processRevision(WikibaseRevisionProcessor.java:88)
    at org.wikidata.wdtk.dumpfiles.MwRevisionProcessorBroker.notifyMwRevisionProcessors(MwRevisionProcessorBroker.java:183)
    at org.wikidata.wdtk.dumpfiles.MwRevisionProcessorBroker.processRevision(MwRevisionProcessorBroker.java:147)
    at org.wikidata.wdtk.dumpfiles.MwRevisionDumpFileProcessor.processXmlRevision(MwRevisionDumpFileProcessor.java:427)
    at org.wikidata.wdtk.dumpfiles.MwRevisionDumpFileProcessor.processXmlPage(MwRevisionDumpFileProcessor.java:345)
    at org.wikidata.wdtk.dumpfiles.MwRevisionDumpFileProcessor.tryProcessXmlPage(MwRevisionDumpFileProcessor.java:282)
    at org.wikidata.wdtk.dumpfiles.MwRevisionDumpFileProcessor.processXmlMediawiki(MwRevisionDumpFileProcessor.java:202)
    at org.wikidata.wdtk.dumpfiles.MwRevisionDumpFileProcessor.processDumpFileContents(MwRevisionDumpFileProcessor.java:155)
    at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processDumpFile(DumpProcessingController.java:546)
    at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processAllRecentRevisionDumps(DumpProcessingController.java:389)
```

**Comment by mkroetzsch** [comment]
It seems to me that the clean solution here would be to have a JSON object for redirects and additional processing methods that are used to handle them. Unfortunately, adding such methods to the interface would make current implementations incomplete. Do you know if there are redirects in JSON dumps or plans to have them there?

**Comment by Tpt** [comment]
+1 for the clean interface.

No, I don't think there are plans for to have redirects in JSON dumps. In these dumps redirects seem to be resolved in statements serializations so there are no need to have them if you just work on one dump.
