### ISSUE TITLE
Failed to run ClassPropertyUsageAnalyzer

### ISSUE THREAD

**Issue by mrpirzado** [Wikidata/Wikidata-Toolkit#255]
I am unable to run ClassPropertyUsageAnalyzer it gives Exception in thread "main" java.lang.NullPointerException: Lower bound cannot be null 

I have downloaded json dump of the wiki data and using locally 
Here is a full stack trace

`Exception in thread "main" java.lang.NullPointerException: Lower bound cannot be null
	at org.apache.commons.lang3.Validate.notNull(Validate.java:222)
	at org.wikidata.wdtk.datamodel.implementation.QuantityValueImpl.<init>(QuantityValueImpl.java:64)
	at org.wikidata.wdtk.datamodel.implementation.DataObjectFactoryImpl.getQuantityValue(DataObjectFactoryImpl.java:117)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.copy(DatamodelConverter.java:339)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.visit(DatamodelConverter.java:608)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.visit(DatamodelConverter.java:72)
	at org.wikidata.wdtk.datamodel.json.jackson.datavalues.JacksonValueQuantity.accept(JacksonValueQuantity.java:107)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.copyValue(DatamodelConverter.java:576)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.deepCopySnak(DatamodelConverter.java:692)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.deepCopyClaim(DatamodelConverter.java:746)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.deepCopyStatement(DatamodelConverter.java:781)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.deepCopyStatementGroup(DatamodelConverter.java:810)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.deepCopyStatementGroups(DatamodelConverter.java:843)
	at org.wikidata.wdtk.datamodel.helpers.DatamodelConverter.copy(DatamodelConverter.java:525)
	at examples.ClassPropertyUsageAnalyzer.processItemDocument(ClassPropertyUsageAnalyzer.java:564)
	at org.wikidata.wdtk.datamodel.interfaces.EntityDocumentProcessorBroker.processItemDocument(EntityDocumentProcessorBroker.java:59)
	at org.wikidata.wdtk.dumpfiles.JsonDumpFileProcessor.handleDocument(JsonDumpFileProcessor.java:130)
	at org.wikidata.wdtk.dumpfiles.JsonDumpFileProcessor.processDumpFileContents(JsonDumpFileProcessor.java:91)
	at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processDumpFile(DumpProcessingController.java:546)
	at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processDump(DumpProcessingController.java:482)
	at examples.ExampleHelpers.processEntitiesFromWikidataDump(ExampleHelpers.java:197)
	at examples.ClassPropertyUsageAnalyzer.main(ClassPropertyUsageAnalyzer.java:492)
Java Result: 1`

**Comment by Tpt** [comment]
This is because the latest released version of WikidataToolkit (0.7) is not compatible with new Wikidata dumps. This bug should not happen if you use the master branch code.

**Comment by Tpt** [comment]
Fixed by version 0.8
