### ISSUE TITLE
Fail cleanly when fetching deleted entity documents

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#379]
Just pasting this here to investigate later:
```
Exception in thread "Thread-8" java.lang.NullPointerException
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForInsertion(StatementUpdate.java:369)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForUpdate(StatementUpdate.java:294)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.<init>(StatementUpdate.java:179)
	at org.wikidata.wdtk.wikibaseapi.TermStatementUpdate.<init>(TermStatementUpdate.java:140)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateTermsStatements(WikibaseDataEditor.java:589)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:145)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:209)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by wetneb** [comment]
This is because we are trying to edit a deleted item. This is what wbgetentities returns:
```
{
    "entities": {
        "Q11410025": {
            "id": "Q11410025",
            "missing": ""
        }
    },
    "success": 1
}
```
We should make sure that fetching entity documents fails for deleted items.

**Comment by wetneb** [comment]
Actually `WikibaseEntityFetcher` itself only returns the entities that could be successfully fetched - so the error handling should probably be done in OpenRefine instead. Closing this.
