### ISSUE TITLE
Fail correctly when receiving 503 errors from Wikibase

### ISSUE THREAD

**Issue by wetneb** [Wikidata/Wikidata-Toolkit#402]
Currently, when `WbGetEntitiesAction` receives a 503 error, it returns an empty Map. It should throw a `MediaWikiApiErrorException` instead.

```
10:37:10.612 [..ting.EditBatchProcessor] Requesting documents (1523ms)
10:39:15.685 [..kibaseapi.ApiConnection] Error: API request returned response code 503 (125073ms)
10:39:15.686 [..api.WbGetEntitiesAction] Could not retrive data: java.io.IOException: Server returned HTTP response code: 503 for URL: https://www.wikidata.org/w/api.php (1ms)
Exception in thread "Thread-8" java.lang.NullPointerException
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForInsertion(StatementUpdate.java:369)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.markStatementsForUpdate(StatementUpdate.java:294)
	at org.wikidata.wdtk.wikibaseapi.StatementUpdate.<init>(StatementUpdate.java:179)
	at org.wikidata.wdtk.wikibaseapi.TermStatementUpdate.<init>(TermStatementUpdate.java:140)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateTermsStatements(WikibaseDataEditor.java:589)
	at org.openrefine.wikidata.editing.EditBatchProcessor.performEdit(EditBatchProcessor.java:145)
	at org.openrefine.wikidata.operations.PerformWikibaseEditsOperation$PerformEditsProcess.run(PerformWikibaseEditsOperation.java:211)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by wetneb** [comment]
Or maybe not a `MediaWikiApiErrorException`, because that is not exactly a MediaWiki error itself (it is not at the same level), but it should definitely throw something! Either:
* don't catch the underlying `IOException` -> that will change the method signature (but that is a good thing: clients will need to think about what to do in that case)
* wrap the IOException as a MediaWiki error, with a new error code;
* throw an unchecked exception??
