### ISSUE TITLE
Nullpointer Exception - RDF Serialization

### ISSUE THREAD

**Issue by Livvi** [Wikidata/Wikidata-Toolkit#407]
Hey,

I am trying to serialize RDF Tripels of the 2018-11-05 json dump, but it always stops after getting this NullPointerException: 

```
WARN  - Could not determine Type of P5193. It is not a valid EntityDocument Id
Exception in thread "main" java.lang.NullPointerException
	at org.wikidata.wdtk.rdf.values.EntityIdValueConverter.getRdfValue(EntityIdValueConverter.java:46)
	at org.wikidata.wdtk.rdf.values.AnyValueConverter.visit(AnyValueConverter.java:95)
	at org.wikidata.wdtk.rdf.values.AnyValueConverter.visit(AnyValueConverter.java:49)
	at org.wikidata.wdtk.datamodel.implementation.FormIdValueImpl.accept(FormIdValueImpl.java:125)
	at org.wikidata.wdtk.rdf.values.AnyValueConverter.getRdfValue(AnyValueConverter.java:90)
	at org.wikidata.wdtk.rdf.SnakRdfConverter.visit(SnakRdfConverter.java:150)
	at org.wikidata.wdtk.rdf.SnakRdfConverter.visit(SnakRdfConverter.java:53)
	at org.wikidata.wdtk.datamodel.implementation.ValueSnakImpl.accept(ValueSnakImpl.java:138)
	at org.wikidata.wdtk.rdf.RdfConverter.writeClaim(RdfConverter.java:391)
	at org.wikidata.wdtk.rdf.RdfConverter.writeStatement(RdfConverter.java:369)
	at org.wikidata.wdtk.rdf.RdfConverter.writeStatements(RdfConverter.java:282)
	at org.wikidata.wdtk.rdf.RdfConverter.writePropertyDocument(RdfConverter.java:190)
	at org.wikidata.wdtk.rdf.RdfSerializer.processPropertyDocument(RdfSerializer.java:141)
	at org.wikidata.wdtk.datamodel.interfaces.EntityDocumentProcessorBroker.processPropertyDocument(EntityDocumentProcessorBroker.java:59)
	at org.wikidata.wdtk.dumpfiles.JsonDumpFileProcessor.handleDocument(JsonDumpFileProcessor.java:129)
	at org.wikidata.wdtk.dumpfiles.JsonDumpFileProcessor.processDumpFileContents(JsonDumpFileProcessor.java:88)
	at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processDumpFile(DumpProcessingController.java:541)
	at org.wikidata.wdtk.dumpfiles.DumpProcessingController.processDump(DumpProcessingController.java:478)
	at examples.ExampleHelpers.processEntitiesFromWikidataDump(ExampleHelpers.java:193)
	at examples.RdfSerializationExample.main(RdfSerializationExample.java:116)
java.io.IOException: Write end dead
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:310)
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377)
	at java.base/java.io.InputStream.read(InputStream.java:205)
	at examples.RdfSerializationExample$1.run(RdfSerializationExample.java:166)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by Tpt** [comment]
It seems that the exception is raised because the stream you write into is dead. The first line (with a "WARN") seems unrelated and a "normal" warning.

**Comment by AlexTichy** [comment]
I'm facing the exact same error although on P6254 instead of P5193, so I'd suggest to re-open this issue.
I found that a null value is returned from the PropertyRegister,setPropertyTypeFromEntityIdValue() method, because it can only handle item and property ids (starting with "Q" or "P" respectively), while in my case a lexeme id starting with "L" was given. 
Notably, P6254 is the "subject lexeme" property and P5193 is the "Property example for forms" property (which is kind of strange and only used once in the whole Wikidata apparently).

**Comment by wetneb** [comment]
@AlexTichy funny that you report this, I have just started to work on the same problem: #422.

**Comment by wetneb** [comment]
@AlexTichy by the way in your case it should be sufficient to just update WDTK to the latest version as support for lexeme-valued properties has been implemented for a while.

**Comment by wetneb** [comment]
Reopening this to determine how exactly we should fail in these scenarios. With #422 we should be able to parse the entities: fine, but how should we fail when trying to convert to RDF a value of unknown type?
