### ISSUE TITLE
exception while trying to import

### ISSUE THREAD

**Issue by luisenriqueramos1977** [Wikidata/Wikidata-Toolkit#440]
Dear friends, 

I am trying to import an item from wikidata.org into a private wikidata for reuse. Following the datafetcher example I sucesfully retrieve the item qx, however when trying to write it in the target wikidata I receive the error pasted at the end.

The code I am using is as follows:

sourceDocument = GetEntityDocPubWikidata.getEntityDoc("Q717");

//sourceDocument is an object of type EntityDocument

 ItemDocument aDocument = (ItemDocument) sourceDocument;
		 			
 ItemDocument newItemDocument = wbde.createItemDocument(aDocument,
					"Wikidata Importing from Source");	       

the error is as follows:
Exception in thread "main" org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [param-invalid] Invalid field used in call: "id", must match id parameter
	at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:65)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:466)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:406)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:716)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:294)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.createItemDocument(WikibaseDataEditor.java:240)
	at wikiloader.EntityDocWriter.main(EntityDocWriter.java:93).

The question si if there is a way to perform this edition of an external item?

Luis Ramos

**Comment by wetneb** [comment]
I expect this happens because you are trying to create a new item with a Qid already set inside. This is not allowed by Wikibase (you have no control over which Qid is attributed to your new item, except by relying on the sequential allocation).

To solve this problem, you would need a way to get a copy of the ItemDocument without its subject Qid. You should be able to use an ItemDocumentBuilder for that.

**Comment by luisenriqueramos1977** [comment]
Dear  Antonin, 

I am trying to figure out how to perform the procedure you recomended me, however I do not find the way out. 

at first, ItemDocumentBuilder, has only two methods I think I can use, forItemId(noid), and fromItemDocument, but I have an EntityDocument, which it is the only option I find in the wbdf is a getEntityDocument, so I do not know how to get an ItemDocument from an EntityDocument. 

I tried this:

ItemDocument itemDocument1 = (ItemDocument) ItemDocumentBuilder.forItemId(noid).fromItemDocument((ItemDocument) sourceDocument).build();

ItemDocument newItemDocument = wbde.createItemDocument(itemDocument1,
					"Wikidata Toolkit example test item creation");

 ItemIdValue newItemId = newItemDocument.getEntityId();


and the result was this:

Exception in thread "main" org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [param-invalid] Invalid field used in call: "id", must match id parameter
	at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:65)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:466)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:406)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:716)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:294)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.createItemDocument(WikibaseDataEditor.java:240)
	at wikiloader.EntityDocWriter.main(EntityDocWriter.java:105)


Thus, I still have the question if there is a method to provide a full "cloning" of an item from  public to private wikidata?, or do we have to perform a full reading of document in source, and rewriting in target'. 


Luis Ramos

**Comment by wetneb** [comment]
When you are doing this:
```java
ItemDocument itemDocument1 = (ItemDocument)ItemDocumentBuilder.forItemId(noid).fromItemDocument((ItemDocument) sourceDocument).build();

ItemDocument newItemDocument = wbde.createItemDocument(itemDocument1, "Wikidata Toolkit example test item creation");

ItemIdValue newItemId = newItemDocument.getEntityId();
```
you are indeed copying the ItemDocument. But as I tried to explain above, you need to modify this ItemDocument to remove the subject id field. So, before calling `build()`, you need to change the id to `ItemIdValue.NULL` which is the value WDTK expects for new item documents.

**Comment by luisenriqueramos1977** [comment]
Dear Antonin, 

I understand what you say, the problem is that I do not figure out how to do that, I do not find what function or method from wikidata api I have to use. I have searched in the examples, and I did not find a similar procedure. 

Could you share some sample code with me?. 

For now, I am writing a bot to do that, which it is not a problem for me, but if there is a procedure, we could share it with the community of developers. 


Luis Ramos

**Comment by wetneb** [comment]
Actually it does seem we don't have a method to do this easily. Perhaps the easiest way to fix this would be to add a `withSubjectId` method to `EntityDocument`, as we have done for other attributes.
