### ISSUE TITLE
getting units qualifiers

### ISSUE THREAD

**Issue by luisenriqueramos1977** [Wikidata/Wikidata-Toolkit#493]
Dear friends, 

I am trying to add unit qualifiers to some values in wikidata, and it has not been possible.

I created the quantity and add the unit as follows:

String percentage = "https://wikidata-dev.pst.ag/wiki/Item:Q2245";//it is neccesary ord for units BigDecimal bdShare = new BigDecimal("10.0");	
QuantityValue aQuantity = Datamodel.makeQuantityValue(bdShare, "percentage");

add try to create the statement as follows:

Statement newStatement10 = StatementBuilder
						.forSubjectAndProperty(newItemIdX, IDpX)
						.withId(statementToModify.getStatementId())
						.withValue(statementToModify.getValue())
						.withQualifiers(statementToModify.getQualifiers())
						.withQualifierValue(IDpY, aQuantity)
						.withReferences(statementToModify.getReferences())
						.build();

But get the following error:

org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorException: [modification-failed] Illegal value: percentage
ilegal float in method WD_Owned_Update
getting owners of Q568106listed as value of P2702
	at org.wikidata.wdtk.wikibaseapi.apierrors.MediaWikiApiErrorHandler.throwMediaWikiApiErrorException(MediaWikiApiErrorHandler.java:65)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.checkErrors(ApiConnection.java:466)
	at org.wikidata.wdtk.wikibaseapi.ApiConnection.sendJsonRequest(ApiConnection.java:406)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.performAPIAction(WbEditingAction.java:716)
	at org.wikidata.wdtk.wikibaseapi.WbEditingAction.wbEditEntity(WbEditingAction.java:294)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateStatements(WikibaseDataEditor.java:530)
	at org.wikidata.wdtk.wikibaseapi.WikibaseDataEditor.updateStatements(WikibaseDataEditor.java:397)
	at ag.pst.ramos.WDreasoner.WD_Utilities.WDupdateDecimalQualifiers(WD_Utilities.java:173)
	at ag.pst.ramos.WDreasoner.UpdateWDfromJenaRule.WD_Owned_Update(UpdateWDfromJenaRule.java:788)
	at ag.pst.ramos.WDreasoner.Jena_Update_Searcher.OntModelUpdate(Jena_Update_Searcher.java:894)
	at ag.pst.ramos.WDreasoner.WD_Update_Searcher.Search_Item(WD_Update_Searcher.java:224)
	at ag.pst.ramos.WDreasoner.WD_Update_Searcher.update_searcher(WD_Update_Searcher.java:94)
	at ag.pst.ramos.WDreasoner.WD_UpdateFolderListener.processEvents(WD_UpdateFolderListener.java:111)
	at ag.pst.ramos.WDreasoner.WD_Feed_Listener_Main.main(WD_Feed_Listener_Main.java:287)

Please, any support is welcomed

Luis Ramos

**Comment by wetneb** [comment]
The problem comes from `Datamodel.makeQuantityValue(bdShare, "percentage")`: the second argument is not expected to be a bare string but the URI of another entity in your Wikibase instance. So this is not a bug :)
